variable "resourcegroup" {}
variable "cogsvcs" {}
variable "subnet" {}
variable "tags" {}
variable "azSearch" {}
variable "asp_public_ip" {}
variable "virtualnetwork" {}
variable "random" {}
variable "environment" {}